language: python
python:
  - 3.5

services:
  - docker

before_install:
  - echo TICKET_SERVER_CMD=test >> docker/.env
  - echo TICKET_SERVER_PORT=9999 >> docker/.env

install:
  - cd docker
  - docker-compose build

script:
  - TICKET_SERVER_CMD=test docker-compose up ticket_server
