version: '2'

services:
  ticket_server:
    build:
      dockerfile: Dockerfile.server
      context: .
    image: ticket-server:1.0
    container_name: ticket_server
    ports:
      - "9999:9999"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: database
    ports:
      - "3307:3307"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ticket
